### ISSUE TITLE
ISO C99

### ISSUE THREAD

**Issue by osx84** [mtgto/SevenZip.swift#1]
Hello. Please fixed build on real device.

/../SevenZip.swift/Sources/CsevenZip/7zCrc.c:180:9 Call to undeclared function '__crc32b'; ISO C99 and later do not support implicit function declarations

/../SevenZip.swift/Sources/CsevenZip/7zCrc.c:189:11 Call to undeclared function '__crc32w'; ISO C99 and later do not support implicit function declarations

/../SevenZip.swift/Sources/CsevenZip/7zCrc.c:212:9 Call to undeclared function '__crc32b'; ISO C99 and later do not support implicit function declarations

/../SevenZip.swift/Sources/CsevenZip/7zCrc.c:221:11 Call to undeclared function '__crc32d'; ISO C99 and later do not support implicit function declarations

**Comment by mtgto** [comment]
Thanks for your reporting.
I can reproduce the issue in iOS 16.6 with iPhone 14.

**Comment by mtgto** [comment]
Release [v0.1.4](https://github.com/mtgto/SevenZip.swift/releases/tag/0.1.4).
To use SevenZip.swift, you have to specify the git revision, not the git tag name.

<img width="494" alt="image" src="https://github.com/mtgto/SevenZip.swift/assets/1213991/deeef16a-9349-4502-8048-a90e8cccff8b">

I test SevenZip.swift on iPhone 14: https://github.com/mtgto/ExampleSevenZip

**Comment by mtgto** [comment]
Release [v0.2.0](https://github.com/mtgto/SevenZip.swift/releases/tag/0.2.0) includes a bit change.
If you have any question, you may write more comments on this issue or create a new issue.
